### ISSUE TITLE
split to lib and bin?

### ISSUE THREAD

**Issue by naturallymitchell** [Freaky/cw#1]
like, as a [Rust package with both a library and a binary?](https://stackoverflow.com/questions/26946646/rust-package-with-both-a-library-and-a-binary)

**Comment by Freaky** [comment]
It's on the TODO.   Will want to clean the code up first, it's all quite tightly-coupled and branchy.

**Comment by Freaky** [comment]
Closing as of 0.6.0.  The API is surely not ideal, but it is split up now.
