### ISSUE TITLE
cw inserting padding in the output

### ISSUE THREAD

**Issue by federicotorrielli** [Freaky/cw#4]
Goodmorning.
There is an unusual behaviour I'm seeing with cw 0.7.0 (from AUR).
Executing any command it returns the correct result but with a tab (or 4 to 6 spaces) in the stdin.

Example: cw vs wc
![image](https://user-images.githubusercontent.com/31370059/111294841-076a2c80-864b-11eb-8f21-f0aa8e6feeb5.png)

The last release was from 2019 so maybe you've already fixed this, but please update the release here and on AUR if so.
Thanks in advance.

**Comment by Freaky** [comment]
It's just fixed field padding, which is common to most wc implementations.  GNU is a special snowflake in that it stats all its input files and sets a field width based on their combined size - and also special-cases the single-input case to disable padding.

e.g. on FreeBSD:

```
❯ cw -l ~/.zshrc
     401 /home/freaky/.zshrc
❯ wc -l ~/.zshrc
     401 /home/freaky/.zshrc
❯ gwc -l ~/.zshrc
401 /home/freaky/.zshrc

❯ wc -l lots-of-lines .zshrc
    1000 lots-of-lines
     401 .zshrc
    1401 total
❯ cw -l lots-of-lines .zshrc
    1000 lots-of-lines
     401 .zshrc
    1401 total
❯ gwc -l lots-of-lines .zshrc
 1000 lots-of-lines
  401 .zshrc
 1401 total
```

I don't particularly feel like there's a good argument for the [added complexity](https://github.com/coreutils/coreutils/blob/86c8dc2e85c0941ec7908cd5a3db7803e7293606/src/wc.c#L618-L676) of the GNU approach.

**Comment by federicotorrielli** [comment]
Well, thanks for the clarification then. I'll just remove the padding manually on output with another piped command then.

**Comment by Freaky** [comment]
That's probably best, anything else is going to be non-portable.  To sum up:

* Free/Net/Open/DragonFly/other BSD/Solaris/Illumos/SmartOS/etc: Static padding on all outputs
* GNU: Dynamic padding if multiple inputs based on total stat() size
* Busybox: Static padding except on single-input single-count.
* uutils coreutils: Unconditional dynamic padding based on total bytes counted

So cw's following the most common approach.
